### ISSUE TITLE
Cannot get sass compiling to work since this past weekend. 

### ISSUE THREAD

**Issue by Endlyss** [codetasty/ext.sass-compiler#1]
Hey guys, 

Sometime at the end of last week, you pushed an update to the sass compiler. 

At this time, all of my scss stopped compiling automatically, unless I compiled it at the source file (meaning that if I saved an scss part file, it would not do anything. It also broke variables for scss part files within subdirectories). 

I noticed that you've now deprecated the inline commenting at the beginning of each file for setting the options, so I figured this was the culprit. Then I saw your option for the codetasty.json file...and for the life of me, I cannot get this to work, and there is not enough info within the documentation for me to get a working file going. 

Currently, I am working on a WordPress website...so the root of the workspace would be within the same directory that you'd find wp-content, wp-admin, etc. (Checkout attached file 1, for reference). 

My SCSS, however, is quite a few directories in...
The path from the root of the site, to the SCSS/SASS files, is: 
wp-content/themes/[theme_name]/lib/frontend/assets/sass/

Within that sass folder, is one core.scss file, and then a parts sub-directory, that I import into the core.scss file. (see attached file 2, for reference) 

So, with that information, and with the information that you provided on the documentation, is this not what my json file should look like? 

`{
    "extension": {
        "sass-compiler": {
            "files": {
                "watch": [
                    "less/*.sass"
                ],
                "source": "wp-content/themes/[theme_name]/lib/frontend/assets/sass/core.sass",
                "output": "wp-content/themes/[theme_name]/lib/frontend/assets/css/core.css"
            }
        }
    }
}`

If not, where am I going wrong? 

![1](https://user-images.githubusercontent.com/3004507/27365133-73e318a4-560c-11e7-9cf7-9d23f1bba6f0.PNG)
![2](https://user-images.githubusercontent.com/3004507/27365134-73e69ee8-560c-11e7-86b8-51e7b12e64a0.PNG)

**Comment by animack** [comment]
Hi @Endlyss,
"watch" property in your configuration file should probably be:
[
 "wp-content/themes/[theme_name]/lib/frontend/assets/sass/*.sass",
 "wp-content/themes/[theme_name]/lib/frontend/assets/sass/parts/*.sass"
]

If the issue persist, please send us an email to support@codetasty.com

**Comment by Endlyss** [comment]
Hey, thanks for gettin back to me, animack

This worked perfectly. Thank you very much! 

Closing as resolved.
